// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvfblbzxztvipzpqvaqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZmJsYnp4enR2aXB6cHF2YXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTI3NTEsImV4cCI6MjA2MDI4ODc1MX0.Xh9gk589sG7McCcDw4EFB4woSDB_HGRzvjzplXH_ecs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);